# Set distribution to Trusty.
#sudo: required
#dist: trusty

# Set language to C++.
language: cpp

# Only do testing on master, develop, release, and hotfix branches.
branches:
  only:
  - master
  - develop
  - /^release-.*$/
  - /^hotfix-.*$/

# For now, only test with g++ 6
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-test-dev
      before_script:
        - export CC=gcc-6
        - export CXX=g++-6
        - export CPPFLAGS='-pedantic -Wall -Wextra -Wconversion -Wshadow'
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-test-dev
      install:
        - pip install --user requests[security]
        - pip install --user cpp-coveralls
      before_script:
        - export CC=gcc-6
        - export CXX=g++-6
        - export CPPFLAGS='-pedantic -Wall -Wextra -Wconversion -Wshadow -g -O0 --coverage'
      after_success:
        - coveralls --verbose --gcov gcov-6 --gcov-options '\--long-file-names --preserve-paths'

# `make test` makes the tests and runs them.
script:
  - make test
